### ISSUE TITLE
Extension stealing keyboard focus

### ISSUE THREAD

**Issue by TheKevJames** [TheKevJames/gnome-shell-extension-transmission-daemon#16]
Reports from extensions.gnome.org:

> This extension works well however causes some strange side-effects that took me a few hours to solve. On my installation it takes constantly the focus away from the open window. On Wayland it causes strange behaviour, keyboard repeats and freeze. On Xorg it only takes the focus away.
> @mehdix

> Same problem of Medhix im my Arch installation
> @ciorci

> The extension is very nice. Unfortunately as medhix said, it takes the focus away and the keyboard acts strangely, totally unusable
> @DevAlien

Clearly there's a problem here as of the 3.32 update (v25), but I've as of yet been unable to reproduce it. If anyone has extra information, that'd be appreciated!

**Comment by TheKevJames** [comment]
Note that v27 introduced a fairly significant re-write in order to support gnome-shell v3.34 -- this issue may no longer occur.

**Comment by p2004a** [comment]
This is still happening. I have Gnome 3.34.3 and this extension at version v27. It's present both on wayland and X11.

I've tried to debug this a bit, I've figured that this happens when "Always show the indicator" is false and transmission isn't running (`PanelMenu` is not visible).

I've tracked down that changing `TransmissionDaemonIndicatorClass.hide` to (add `this.visible` check):
```js
if (!this._always_show && this.visible) {
    this.visible = false;
}
```
fixes the bug.

I've also noticed that it's not the only bug related to focus. In the not connected state the operation "click transmission indicator to show menu, click to hide it" toggles the focus of window:

1. Window A has focus.
2. Click indicator, menu shows up
3. Click indicator, menu hides and windows A loses focus (under X, focus has window with id 0, checked with `xprop -root _NET_ACTIVE_WINDOW`)
4. Click indicator, menu shows up
5. Click indicator, menu shows hides and windows A (not any random window) regains focus.

This doesn't happen with any other extensions that use `PanelMenu` eg. [OpenWeather](https://extensions.gnome.org/extension/750/openweather/).

Now, I have _not clue_ about developing Gnome extensions, thus I don't know how the proper fix looks like. Above snippet looks more like a workaround to me, but I hope that this description is helpful :wink:.

**Comment by TheKevJames** [comment]
@p2004a this bug has been a nightmare-and-a-half to track down, so thank you for all your efforts! I've just submitted v28 to extensions.gnome with [your suggested fix](https://github.com/TheKevJames/gnome-shell-extension-transmission-daemon/commit/7be3ee74abe2d51bf65132cc3271172f85de7959) -- even if it doesn't fix the problem entirely, hopefully it improves things a bit!

Thanks for the additional debugging info as well -- that gives me a good direction to focus efforts, at least. I'll dig into the OpenWeather codebase and see if that sparks any ~joy~ ideas. If you find anything else, I'd love to hear about it!

I don't know what it is about this bug, but I've just never been able to replicate it no matter what I try. I'm sure its something simple I'm missing, but isn't that always the case...

**Comment by rastersoft** [comment]
It seems that this bug has re-appeared in Gnome Shell 3.36: If I play a video (I tested it with MPV and VLC), while in window mode everything works fine, but if I double click or press F to change to full screen mode, the window losses the focus and I must do a click to be able to continue to manage it with the keyboard.

(but I don't remember problems with Gnome Shell 3.34 or previous)

**Comment by rastersoft** [comment]
I found how to fix it. I uploaded a patch.

**Comment by TheKevJames** [comment]
I've pushed release v29 with @rastersoft's fix (thanks again!). Hopefully this is the last of it (crossed fingers).

**Comment by TheKevJames** [comment]
We've not received a report of this in two months -- closing this as resolved. Thanks again for contributing the various fixes here, folks!
